# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_Xd9Ygi0b92USsW78KD4ipKunQqXrdZ
"""

def fibo(n):
  lista = [1,1]
  for i in range(1,n):
    x = lista[i]+lista[i-1]
    lista.append(x)
  return lista

fibo(4)